nomis-oauth:
  base-url: https://sign-in-dev.hmpps.service.justice.gov.uk/auth

spring:
  r2dbc:
    url: r2dbc:postgresql://${RDS_INSTANCE_ENDPOINT}/${DATABASE_NAME}?currentSchema=${database.schema.name}&stringtype=unspecified&sslmode=verify-full
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  flyway:
    enabled: true
    locations: classpath:db/migration
    user: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    url: jdbc:postgresql://${RDS_INSTANCE_ENDPOINT}/${DATABASE_NAME}?currentSchema=${database.schema.name}