nomis-oauth:
  base-url: https://sign-in-dev.hmpps.service.justice.gov.uk/auth

database:
  name: hmpps_court_case_service_db
  endpoint: localhost:5432
  username: admin
  password: password

spring:
  r2dbc:
    url: r2dbc:postgresql://${database.endpoint}/${database.name}?currentSchema=${database.schema.name}&stringtype=unspecified&sslmode=verify-full
    username: ${database.username}
    password: ${database.password}

  flyway:
    enabled: true
    locations: classpath:db/migration
    user: ${database.username}
    password: ${database.password}
    url: jdbc:postgresql://${database.endpoint}/${database.name}?currentSchema=${database.schema.name}
